services:
  - type: web
    name: instaboostpro
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: /tmp/sqlite.db
